### ISSUE TITLE
Library is not compatible with the NodeMCU

### ISSUE THREAD

**Issue by scottchiefbaker** [valmat/LedMatrix#3]
I'm able to compile the examples on my Uno just fine, but if I switch the board type to NodeMCU I get the attached compile errors.

[NodeMCUErrors.txt](https://github.com/valmat/LedMatrix/files/2801588/nodemcu.txt)

**Comment by valmat** [comment]
Hi, Scott!
I tried to fix this issue in branch [issue#3](https://github.com/valmat/LedMatrix/tree/issue%233)
Please, switch to this branch and check if the fix is working fine.

```bash
cd /path/to/LedMatrix
git fetch
git checkout issue#3
```

**Comment by scottchiefbaker** [comment]
Definitely less errors, but still a couple. Looks like it doesn't like the `max()` calls?

[node-errors.txt](https://github.com/valmat/LedMatrix/files/2818843/node-errors.txt)

**Comment by valmat** [comment]
I [fixed](https://github.com/valmat/LedMatrix/commit/ae30674429b2c96c449ed89bb5a4639c32ca2690#diff-617765cd4619ced743611503a7f0c2e3R218). Please try again.

**Comment by scottchiefbaker** [comment]
Getting closer.

[more-errors.txt](https://github.com/valmat/LedMatrix/files/2829042/more-errors.txt)

**Comment by valmat** [comment]
I installed NodeMcu board into my arduino ide, so now no compilation errors appear.

**Comment by scottchiefbaker** [comment]
Can confirm... library compiles now. Thank you!

**Comment by valmat** [comment]
Thank you for your bug report.
